### ISSUE TITLE
Horrible Bug

### ISSUE THREAD

**Issue by andricDu** [icgc-dcc/SONG#65]
https://github.com/icgc-dcc/SONG/blob/8b0c0abb836f49746fe6b28eb349b2d93e94ed71/song-client/src/main/java/org/icgc/dcc/song/client/register/RestClient.java#L122-L124

This bug is horrifying and just cost us a few hours. It's masking an IO error as a bad access token. Our server wasn't even running and the client was reporting a 401 with the text `invalid token`. The client should **never** infer a HTTP response code that wasn't sent by the server. 

We may need to redo the error handling on the client.

**Comment by rtisma** [comment]
refer to PR:
https://github.com/icgc-dcc/SONG/pull/68
